services:
  - type: web
    name: manicure-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        value: "8312388794:AAEBvJwzbz750q3AckSocpdGYSK9Gbv2eUI"
      - key: ADMIN_ID
        value: "465630314"
